services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        -   "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.2
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: yourpassword
    ports:
        - "3309:3306" #troquei a porta para o host não conflitar com o mysql de outros projetos
    volumes:
      - dbdata:/var/lib/mysql

volumes:
    dbdata:
      driver: local
